name : CI - Calidad y pruebas
on :
  push: 
    branches: ["main","dev","ft/*"]
  pull_request:
    branches: ["main"]
jobs :
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4

      - name: Instalar pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Instalar dependencias
        run: pnpm install --frozen-lockfile

      - name: Revisar Calidad (lint)
        run : pnpm lint

      - name: Probar contruccion de Docker (sin subir)
        run : docker build .
        

